global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using Parking.App.Helpers;
global using Parking.App.Helpers.Card;
global using Parking.App.Models;
global using Parking.App.Models.Config;
global using Parking.App.Models.Dto.Parking.ParkingTicket;
global using Parking.App.Models.Dto.Vehicle.LicensePlate;
global using Parking.App.Models.Tickets;
global using Parking.App.Services;
global using Parking.App.Services.Interfaces;
global using Parking.App.Utilities;
global using Parking.App.ViewModels.Componens;
global using Parking.App.ViewModels.Components;
global using Parking.App.ViewModels.Pages;
global using Parking.App.ViewModels.Windows;
global using Parking.App.Views.Components;
global using Parking.App.Views.Pages;
global using Parking.App.Views.Windows;
global using Parking.Domain.Contracts;
global using Parking.Infrastructure.Context;
global using Parking.Infrastructure.Uow;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using Wpf.Ui;
global using Wpf.Ui.Controls;
global using Application = System.Windows.Application;
global using ComboBox = System.Windows.Controls.ComboBox;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
//global using Color = System.Windows.Media.Color;
global using UserControl = System.Windows.Controls.UserControl;
