<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>wpfui-icon.ico</ApplicationIcon>
		<Configurations>Debug;Release;DebugWithANPR</Configurations>
		<UseWindowsForms>True</UseWindowsForms>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<Version>1.0.16</Version>
	</PropertyGroup>
	<PropertyGroup>
		<BuildDate>$([System.DateTime]::Now.ToString("yyyy-MM-dd"))</BuildDate>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="BuildDateAttribute">
			<_Parameter1>$(BuildDate)</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	<ItemGroup>
		<None Remove="Assets\connection.png" />
		<None Remove="Assets\database.png" />
		<None Remove="Assets\Fonts\IRANYekanXFaNum-Bold.ttf" />
		<None Remove="Assets\Fonts\IRANYekanXFaNum-Regular.ttf" />
		<None Remove="Assets\iran.png" />
		<None Remove="Assets\loading-bar.png" />
		<None Remove="Assets\Madaar-Logo.png" />
		<None Remove="Assets\nfc.png" />
		<None Remove="Assets\no-internet.png" />
		<None Remove="Assets\placeholder.png" />
		<None Remove="Assets\profile.png" />
		<None Remove="Assets\Splash.png" />
		<None Remove="Assets\wpfui-icon-256.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\database.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Content Include="Assets\Madaar-Logo.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\nfc.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\placeholder.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\profile.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\Splash.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<SplashScreen Include="splash.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</SplashScreen>
		<Content Include="wpfui-icon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Coravel" Version="6.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.14">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.3" />
		<PackageReference Include="MiFare" Version="1.1.3" />
		<PackageReference Include="Nager.VideoStream" Version="1.2.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RJCP.SerialPortStream" Version="3.0.2" />
		<PackageReference Include="Serilog" Version="4.2.0" />
		<PackageReference Include="Serilog.Enrichers.ClientInfo" Version="2.1.2" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
		<PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
		<PackageReference Include="WPF-UI" Version="4.0.2" />
		<PackageReference Include="WPF-UI.Abstractions" Version="4.0.2" />
		<PackageReference Include="WPF-UI.DependencyInjection" Version="4.0.2" />
		<PackageReference Include="WPF-UI.Tray" Version="4.0.2" />
		<PackageReference Include="WPF-UI.Violeta" Version="4.0.2.2" />
		<PackageReference Include="ZXing.Net" Version="0.16.10" />
		<PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.13" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\Fonts\IRANYekanXFaNum-Bold.ttf">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Fonts\IRANYekanXFaNum-Regular.ttf">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Content Include="Assets\iran.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Resource Include="Assets\connection.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\loading-bar.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\no-internet.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\wpfui-icon-256.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Parking.Domain\Parking.Domain.csproj" />
		<ProjectReference Include="..\Parking.Infrastructure\Parking.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="OmidPayPcPos">
			<HintPath>OmidPayPcPos.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Assets\car-dark.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\car-light.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\car-red.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\cloud-dark.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\cloud-light.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\icon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Assets\ServerIconUpdate.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<None Update="wpfui-icon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
