//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.App {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Appearance_Theme {
            get {
                return ((string)(this["Appearance_Theme"]));
            }
            set {
                this["Appearance_Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Appearance_ShowLatestExited {
            get {
                return ((bool)(this["Appearance_ShowLatestExited"]));
            }
            set {
                this["Appearance_ShowLatestExited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Appearance_ShowLatestEntry {
            get {
                return ((bool)(this["Appearance_ShowLatestEntry"]));
            }
            set {
                this["Appearance_ShowLatestEntry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Appearance_ShowLatestTicket {
            get {
                return ((bool)(this["Appearance_ShowLatestTicket"]));
            }
            set {
                this["Appearance_ShowLatestTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Appearance_UpdateListInterval {
            get {
                return ((int)(this["Appearance_UpdateListInterval"]));
            }
            set {
                this["Appearance_UpdateListInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Appearance_InvoiceShowTime {
            get {
                return ((int)(this["Appearance_InvoiceShowTime"]));
            }
            set {
                this["Appearance_InvoiceShowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Camera_ExitCameraEnable {
            get {
                return ((bool)(this["Camera_ExitCameraEnable"]));
            }
            set {
                this["Camera_ExitCameraEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_ExitCameraUrl {
            get {
                return ((string)(this["Camera_ExitCameraUrl"]));
            }
            set {
                this["Camera_ExitCameraUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_ExitCameraUser {
            get {
                return ((string)(this["Camera_ExitCameraUser"]));
            }
            set {
                this["Camera_ExitCameraUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_ExitCameraPass {
            get {
                return ((string)(this["Camera_ExitCameraPass"]));
            }
            set {
                this["Camera_ExitCameraPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Camera_MainCameraEnable {
            get {
                return ((bool)(this["Camera_MainCameraEnable"]));
            }
            set {
                this["Camera_MainCameraEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_MainCameraUrl {
            get {
                return ((string)(this["Camera_MainCameraUrl"]));
            }
            set {
                this["Camera_MainCameraUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_MainCameraUser {
            get {
                return ((string)(this["Camera_MainCameraUser"]));
            }
            set {
                this["Camera_MainCameraUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_MainCameraPass {
            get {
                return ((string)(this["Camera_MainCameraPass"]));
            }
            set {
                this["Camera_MainCameraPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Camera_ANPR_Enable {
            get {
                return ((bool)(this["Camera_ANPR_Enable"]));
            }
            set {
                this["Camera_ANPR_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte Camera_ANPR_FrameSkip {
            get {
                return ((byte)(this["Camera_ANPR_FrameSkip"]));
            }
            set {
                this["Camera_ANPR_FrameSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public short Camera_ANPR_VlcCache {
            get {
                return ((short)(this["Camera_ANPR_VlcCache"]));
            }
            set {
                this["Camera_ANPR_VlcCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Camera_ANPR_PlateType {
            get {
                return ((byte)(this["Camera_ANPR_PlateType"]));
            }
            set {
                this["Camera_ANPR_PlateType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public byte Camera_ANPR_LightParameter {
            get {
                return ((byte)(this["Camera_ANPR_LightParameter"]));
            }
            set {
                this["Camera_ANPR_LightParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte Camera_ANPR_PlateCountInBuffer {
            get {
                return ((byte)(this["Camera_ANPR_PlateCountInBuffer"]));
            }
            set {
                this["Camera_ANPR_PlateCountInBuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public float Camera_ANPR_Cnf {
            get {
                return ((float)(this["Camera_ANPR_Cnf"]));
            }
            set {
                this["Camera_ANPR_Cnf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Camera_ANPR_Economy {
            get {
                return ((bool)(this["Camera_ANPR_Economy"]));
            }
            set {
                this["Camera_ANPR_Economy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POS_Type {
            get {
                return ((string)(this["POS_Type"]));
            }
            set {
                this["POS_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POS_Connection_Type {
            get {
                return ((string)(this["POS_Connection_Type"]));
            }
            set {
                this["POS_Connection_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POS_IP {
            get {
                return ((string)(this["POS_IP"]));
            }
            set {
                this["POS_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int POS_Port {
            get {
                return ((int)(this["POS_Port"]));
            }
            set {
                this["POS_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Application_GateType {
            get {
                return ((string)(this["Application_GateType"]));
            }
            set {
                this["Application_GateType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_PrintInvoiceAfterEntry {
            get {
                return ((bool)(this["Application_PrintInvoiceAfterEntry"]));
            }
            set {
                this["Application_PrintInvoiceAfterEntry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Application_DefaultVehicleSegmentPrice {
            get {
                return ((int)(this["Application_DefaultVehicleSegmentPrice"]));
            }
            set {
                this["Application_DefaultVehicleSegmentPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500000")]
        public decimal Application_MissingCardPrice {
            get {
                return ((decimal)(this["Application_MissingCardPrice"]));
            }
            set {
                this["Application_MissingCardPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_GatePCName {
            get {
                return ((string)(this["Application_GatePCName"]));
            }
            set {
                this["Application_GatePCName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_DbActiveStatus {
            get {
                return ((bool)(this["Application_DbActiveStatus"]));
            }
            set {
                this["Application_DbActiveStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_DbHostAddress {
            get {
                return ((string)(this["Application_DbHostAddress"]));
            }
            set {
                this["Application_DbHostAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_DbUsername {
            get {
                return ((string)(this["Application_DbUsername"]));
            }
            set {
                this["Application_DbUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_DbPassword {
            get {
                return ((string)(this["Application_DbPassword"]));
            }
            set {
                this["Application_DbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_DbName {
            get {
                return ((string)(this["Application_DbName"]));
            }
            set {
                this["Application_DbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_ServerAddress {
            get {
                return ((string)(this["Application_ServerAddress"]));
            }
            set {
                this["Application_ServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_Logging {
            get {
                return ((bool)(this["Application_Logging"]));
            }
            set {
                this["Application_Logging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte Application_LoggingFileSize {
            get {
                return ((byte)(this["Application_LoggingFileSize"]));
            }
            set {
                this["Application_LoggingFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public byte Application_LoggingFileCount {
            get {
                return ((byte)(this["Application_LoggingFileCount"]));
            }
            set {
                this["Application_LoggingFileCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://188.213.66.252:8090/api")]
        public string Application_ApiServerAddress {
            get {
                return ((string)(this["Application_ApiServerAddress"]));
            }
            set {
                this["Application_ApiServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Application_Sync_Interval_CountOfTake {
            get {
                return ((int)(this["Application_Sync_Interval_CountOfTake"]));
            }
            set {
                this["Application_Sync_Interval_CountOfTake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Application_Sync_Interval_Second {
            get {
                return ((int)(this["Application_Sync_Interval_Second"]));
            }
            set {
                this["Application_Sync_Interval_Second"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_Logging_In_Elastic {
            get {
                return ((bool)(this["Application_Logging_In_Elastic"]));
            }
            set {
                this["Application_Logging_In_Elastic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_Logs_Elastic_Server {
            get {
                return ((string)(this["Application_Logs_Elastic_Server"]));
            }
            set {
                this["Application_Logs_Elastic_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_Logs_Elastic_Username {
            get {
                return ((string)(this["Application_Logs_Elastic_Username"]));
            }
            set {
                this["Application_Logs_Elastic_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_Logs_Elastic_Pass {
            get {
                return ((string)(this["Application_Logs_Elastic_Pass"]));
            }
            set {
                this["Application_Logs_Elastic_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_PlateCheckInExitGate {
            get {
                return ((bool)(this["Application_PlateCheckInExitGate"]));
            }
            set {
                this["Application_PlateCheckInExitGate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_EntryCardRequirement {
            get {
                return ((bool)(this["Application_EntryCardRequirement"]));
            }
            set {
                this["Application_EntryCardRequirement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Application_Sync_Enable {
            get {
                return ((bool)(this["Application_Sync_Enable"]));
            }
            set {
                this["Application_Sync_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExitGate")]
        public string Application_DeviceId {
            get {
                return ((string)(this["Application_DeviceId"]));
            }
            set {
                this["Application_DeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Application_EnableSyncImage {
            get {
                return ((bool)(this["Application_EnableSyncImage"]));
            }
            set {
                this["Application_EnableSyncImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application_MainPage_ReloadShortcut {
            get {
                return ((string)(this["Application_MainPage_ReloadShortcut"]));
            }
            set {
                this["Application_MainPage_ReloadShortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_DetectLatinPlate {
            get {
                return ((bool)(this["Application_DetectLatinPlate"]));
            }
            set {
                this["Application_DetectLatinPlate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Appearance_ShowBarcodeSearchBox {
            get {
                return ((bool)(this["Appearance_ShowBarcodeSearchBox"]));
            }
            set {
                this["Appearance_ShowBarcodeSearchBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Application_Sync_EnableSyncLicensePlateGroup {
            get {
                return ((bool)(this["Application_Sync_EnableSyncLicensePlateGroup"]));
            }
            set {
                this["Application_Sync_EnableSyncLicensePlateGroup"] = value;
            }
        }
    }
}
